### PR TITLE
Travis should turn red when unit tests fail

### PR DESCRIPTION
**Pull request by rijobro**
Addresses #192.

### CODE REVIEW

**Comment by rijobro** [comment]
@casperdcl the docker builds are still red on travis. Is this intentional?

https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/builds/483407696

**Comment by casperdcl** [comment]
hmm the last successful docker push according to https://hub.docker.com/r/ccppetmr/sirf/tags was 2 days ago - has anything changed in the testing framework changed over the last couple of days? If so that would probably have to be duplicated in the docker build scripts...

**Comment by casperdcl** [comment]
ah these are two separate issues. let's merge #194 and open a new one for docker elsewhere

**Comment by casperdcl** [comment]
continued in #195

**Pull request merged**
