### PR TITLE
Docker: add a service image with jupyter etc

### LINKED ISSUE #216: docker: service
Have a headless docker service container running jupyter, gadgetron, etc... similar to https://github.com/CCPPETMR/CCPPETMR_VM/issues/117. This allows:

```bash
docker start sirf && firefox localhost:8888
```

### PR DESCRIPTION
**Pull request by casperdcl**
A headless docker service container running jupyter, gadgetron, etc. This allows:

```bash
docker start sirf && firefox localhost:9999
```

- [x] create new service image tag `ccppetmr/sirf:service`
  + [x] automate on travis `:service`, `:$TRAVIS_TAG-service`, `:release-service`, `:devel-service`, etc?
- [x] install `jupyter`
- [x] autostart `gadgetron:9002` & `jupyter:9999`
  + [x] ensure graceful stop
  + [x] ensure scalability (one machine hosting multiple containers)
- [x] possibly expose `jupyter` on a port other than `8888` (`9999`, as with #218)?
- [x] add some notebooks examples in the `/devel` folder for quickstart!
  + [ ] maybe use `/opt/SIRF-SuperBuild/devel` or `/opt/SIRF-SuperBuild/` as a `jupyter` root instead?
- [x] documentation
- [ ] install optional dependencies (see https://github.com/CCPPETMR/SIRF-SuperBuild/pull/214#discussion_r261791440) such as `hdfview`, `h5utils`, ...?
----
- fixes #216
- related: https://github.com/CCPPETMR/CCPPETMR_VM/issues/117
- related: https://github.com/CCPPETMR/CCPPETMR_VM/issues/101

### CODE REVIEW

**Comment by casperdcl** [comment]
Currently `ccppetmr/sirf:service`: 4.35GB

**Comment by casperdcl** [comment]
@KrisThielemans FYI if you want to run a hackathon, provided you provide machines all connected to a network (e.g. a lab at a uni) then you can host multiple docker containers (running on different ports for different people to connect to) for free.

Can always run multiple containers in the cloud as well for nearly nothing.

**Comment by casperdcl** [comment]
@KrisThielemans questions I need answered regarding Jupyter (see PR description):

- use a port other than `8888`?
- what directory to use as root?
- add some notebooks from somewhere?

**Comment by KrisThielemans** [comment]
- I see no reason to change the default port. I think it's a bit different on Azure where people have to type full URL anyway, but I don't really mind. @bathomas, did you have  reason to select `9999`.
- I'd clone https://github.com/CCPPETMR/SIRF-Exercises, `cd` there and start the server there. It does limit where can go of course, but it's cleanest.

great stuff. thanks

**Comment by casperdcl** [comment]
@KrisThielemans 
- use e.g. `9999` because the host machine may already have jupyter running and bound to `8888`
- we should also be consistent (docker, Azure, VM etc should try to build the same way, i.e. #91, and expose the same ports, example folders etc)

**Comment by casperdcl** [comment]
@KrisThielemans think this is ready for merge if you're happy

**Comment by KrisThielemans** [comment]
oh, please add a few lines to `CHANGES.md`

**Pull request merged**
