### PR TITLE
update CIL framework to point to current master

### PR DESCRIPTION
**Pull request by rijobro**

### CODE REVIEW

**Comment by rijobro** [comment]
Both this PR and the master seem to be in the same state. Travis is happy for all builds except Docker. The Docker errors look unrelated to this PR.

**Comment by KrisThielemans** [comment]
These are the same jobs that were failing earlier since your previous PR, which flipped the situation between the 3rd job failing, to 3 others failing. 

I think the docker builds are the currently the only ones that try to build CIL (as @rijobro disabled the direct tests).

https://travis-ci.org/github/CCPPETMR/SIRF-SuperBuild/jobs/663922430#L1584
still says
```
CMake Error: The source directory "/opt/SIRF-SuperBuild/sources/CCPi-Framework" does not appear to contain CMakeLists.txt.
```

**Comment by rijobro** [comment]
It's hard to say what's going on as the output of different dependencies are overlapping. But it looks like it's getting old CCPi-Framework commit (`9bd69b7 fix MixedL21Norm (#417)`, [this line](https://travis-ci.org/github/CCPPETMR/SIRF-SuperBuild/jobs/663922430#L1576)).

Is it possible that Docker uses the tags differently? Or caches them? Otherwise, I don't really see where I could have gone wrong (desired commit was `adf4163`).

**Comment by rijobro** [comment]
> @rijobro please add this TAG for CCPi-Astra 8c2493710f5eac1316945585fe6333ab56f9a2a1

Done.

Presumably, it still doesn't solve the Docker issue though. @KrisThielemans , @casperdcl the Docker must be working on a different logic for checking out branches?

**Comment by KrisThielemans** [comment]
I vaguely recall that the docker image just gets updated (as opposed to created from scratch at every build), which would make a lot of sense. So we might be hitting something like #257

**Comment by rijobro** [comment]
I vaguely recall Docker only updating once something was in master? I'll merge this and see if it solves that problem.

**Comment by casperdcl** [comment]
If you want to test docker in PRs you'll need to temporarily update https://github.com/CCPPETMR/SIRF-SuperBuild/blob/c5b52b21661d5997a76528124c317eadd5ce21ec/docker/user_sirf-ubuntu.sh#L6

**Pull request merged**
