### PR TITLE
flexible version tagging

### PR DESCRIPTION
**Pull request by paskino**
Enables flexible version tagging for Gadgetron, SIRF, STIR and ISMRMRD.

Devel build (1/0) : latest master from upstream, stable SIRF 0.9.0 versions
Additionally one may specify which URL/TAG to use for any of the sub-projects.

### CODE REVIEW

**Comment by paskino** [comment]
`OPTION`s are boolean so they cannot be used for what you want.

**Comment by KrisThielemans** [comment]
Travis worked (which is great news as it means we're still ok with Gadgetron and STIR master).

I did notice that setting `DEVEL_BUILD=On` after the first configure doesn't reset the `GIT_TAG`s. That seems unavoidable (but might mean that `DEVEL_BUILD` shouldn't be a cached variable. Possibly @bathomas or @casperdcl has some ideas on this.

Finally, I think it would be good to prefix all these advanced variables with the same thing. That makes it easier to find them (e.g. when displaying as "Grouped" in CMake. Maybe `SB_SIRF_TAG` (for "SuperBuild") or so?

**Comment by paskino** [comment]
I've added the build with `DEV_BUILD=ON` to travis and it works.

**Comment by paskino** [comment]
I've noticed that the advanced variables get grouped anyway by package name: SIRF, ISMRMRD, Gadgetron  and STIR, which is maybe even better.

**Pull request merged**
