### PR TITLE
use system boost by default because of #63

### PR DESCRIPTION
**Pull request by paskino**

### CODE REVIEW

**Comment by rijobro** [comment]
@KrisThielemans - as requested, the info telling Mac users to upgrade to Boost 1.66 is given [here](https://github.com/CCPPETMR/SIRF/wiki/SIRF-SuperBuild-on-MacOS#2-boost-). I wonder if it's not in an obvious enough location?

**Comment by KrisThielemans** [comment]
sorry to be late. I thought we'd only do this for OSX and Windows, but keep it OFF elsewhere. @bathomas, @casperdcl any opinions?

**Comment by paskino** [comment]
No worries. I misunderstood your email. 
I'll add a switch `if not UNIX`

**Comment by KrisThielemans** [comment]
@rijobro we'll now require it, so it needs to be moved up to "requirements". sorry

**Comment by bathomas** [comment]
Seems unnecessary to default to `ON` for an OS that doesn't have a problem. SIRF(-SuperBuild) is straightforward to use on Ubuntu. Also, the packaged version would be older (1.54?) on Travis.

**Comment by paskino** [comment]
The Superbuild is actually building Boost 1.63. Wouldn't it be sufficient to upgrade the built (required) version to 1.66?

**Comment by rijobro** [comment]
It wouldn't be sufficient - Brew's version of 1.66 solves the problem on OSX (thus why `USE_SYSTEM_Boost` works). 

But the problem is still there with the boostrapped version 1.66 of boost (the one that will be installed by the superbuild).

**Comment by bathomas** [comment]
As @KrisThielemans said, I think `USE_SYSTEM_Boost` should be `OFF` for Linux systems and `ON` for the others.

**Comment by paskino** [comment]
OK, then I'll add the switch for non Unix. 
Can we fix our own compilation of Boost on MacOSX?

**Comment by rijobro** [comment]
I looked into this before. We install Boost with `./bootsrap.sh` and then `./b2 install`, so in one of those two we would have to add an option that would install the absolute paths to the dynamic libraries. So far, I haven't found a way of doing that.

**Comment by rijobro** [comment]
Or maybe, add the switch `if OSX` in CMake, and build Boost with static libs if true?

**Comment by paskino** [comment]
To be clear, on OSX the only way to have the SuperBuild working is to install Boost 1.66 with `brew`

**Comment by paskino** [comment]
@rijobro what about this https://stackoverflow.com/questions/3431619/how-to-force-boost-to-use-rpath and especially `hardcode-dll-paths=true dll-path=/custom/path/lib`

**Comment by rijobro** [comment]
I tried that before with no luck (might be out of date). I'll try again and let you know.

**Comment by rijobro** [comment]
Tried again with no effect (maybe outdated?)

**Pull request merged**
