### PR TITLE
[TRAVIS] fix DEVEL_BUILD

### PR DESCRIPTION
**Pull request by KrisThielemans**
required for recent Gadgetron

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@casperdcl how do we switch the docker devel build to use gcc6?

**Comment by KrisThielemans** [comment]
something wrong in our Travis file as it ignores the `CC=gcc-6` settings. Checking [a log](https://api.travis-ci.org/v3/job/463585998/log.txt) I find
```
$ export EXTRA_BUILD_FLAGS="-DDEVEL_BUILD=ON -DUSE_SYSTEM_Boost=OFF -DUSE_SYSTEM_FFTW3=OFF -DUSE_SYSTEM_HDF5=OFF -DUSE_SYSTEM_SWIG=OFF"
$ export CC=gcc-6
$ export CXX=g++-6
$ export PYMVER=2

$ export TRAVIS_COMPILER=g++
$ export CXX=g++
$ export CXX_FOR_BUILD=g++
$ export CC=gcc
$ export CC_FOR_BUILD=gcc
```
Anyone? @casperdcl ?

**Comment by paskino** [comment]
I used to set `CMAKE_CXX_COMPILER` and `CMAKE_C_COMPILER` variables issuing CMake on our cluster to get it pick the right compiler.

**Comment by paskino** [comment]
First, I don't find where this variables are set. 

However in the [`.travis.yml`](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/travis_gcc6/.travis.yml#L41) I see
```
addons:
      apt:
        sources:
         - ubuntu-toolchain-r-test
        packages:
            - g++-6
```
which seems to imply that we install the `g++-6` package from `ubuntu-toolchain-r-test`.  I do not find that package at [their website](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+packages), only `gcc-6`. Maybe I'm totally wrong. 

At any rate the `gcc-6` package does not contain a binary `g++-6`.

**Comment by paskino** [comment]
On my 16.04 VM
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-cache search g++-6

> clang-6.0 - C, C++ and Objective-C compiler
> clang-6.0-doc - C, C++ and Objective-C compiler - Documentation
> clang-6.0-examples - Clang examples
> libclang-6.0-dev - clang library - Development package
> python-clang-6.0 - Clang Python Bindings
```

**Comment by KrisThielemans** [comment]
I have no idea about the toolchain-r, but g++-6 is installed ok. we can even get g++-8 there. you can see it in the log (link above).

The problem is just the setting of the environment variables in Travis. we set them for each configuration (e.g. [here](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/894010dc8d67d0e6c87aee5b424162363eee4823/.travis.yml#L71), as the compilers are different for each config. That's ok as you can see in the log and my quote in the first post. However, then Travis overrides them with something else, presumably because of how our yml file is. (We needed to [set the config to python](https://github.com/CCPPETMR/SIRF-SuperBuild/blob/894010dc8d67d0e6c87aee5b424162363eee4823/.travis.yml#L66) to get that side to work).

**Comment by KrisThielemans** [comment]
@paskino, please revert this /82b09356a52acafd75bb6333a141b8f9bfbe4146 commit.

NOT all configs use gcc6. we will want to be able to use different compilers.

Also, using the CMake flags doesn't transport to boost, fftw etc, see #14.

**Comment by paskino** [comment]
Of course, but how would I check if the changes work?

**Comment by KrisThielemans** [comment]
remaining failures are due to a problem with Gadgetron master https://github.com/gadgetron/gadgetron/pull/715

**Comment by casperdcl** [comment]
just to note that only 2 docker images are built: standard and devel (ubuntu 16.04, gcc5)

see default flags here: https://github.com/CCPPETMR/SIRF-SuperBuild/blob/c3a2c065e3ff0358b8b2c3dbf9961268b2f03cc0/docker/Dockerfile#L78-L82

**Pull request merged**
