### PR TITLE
attempt to fix travis OSX

### PR DESCRIPTION
**Pull request by rijobro**
Addresses https://github.com/CCPPETMR/SIRF-SuperBuild/issues/292 as per https://github.com/CCPPETMR/SIRF/pull/470

### CODE REVIEW

**Comment by KrisThielemans** [comment]
Travis jobs cancelled in an attempt to get the v2.1.0 jobs going. Please restart them once v2.1.0 is out. Apologies

**Comment by rijobro** [comment]
@casperdcl: Thanks, I'm just going to merge all builds bar the one you just removed are green.

**Comment by casperdcl** [comment]
I've cancelled the branch and PR builds too. `master` (https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/builds/615103876) should be fine.

**Comment by rijobro** [comment]
Good call.

**Pull request merged**
