### PR TITLE
use canonical dir names in swig and fftw for win32

### LINKED ISSUE #16: make location of output of SuperBuild consistent
some projects (probably CMake-ones) have their build in `x-prefix/src/x-build` as opposed to `x-build`.

Also, INSTALL is currently hard-wired but should honour `CMAKE_INSTALL_PREFIX`.

### PR DESCRIPTION
**Pull request by paskino**
closes #16

### CODE REVIEW

**Comment by rijobro** [comment]
not sure how this closes #16 though.

**Comment by KrisThielemans** [comment]
> not sure how this closes #16 though.

Maybe this is the last of a long road?

**Comment by paskino** [comment]
That's right. We had some remnants directories for the Windows builds that didn't get into the canonical directories.

**Comment by rijobro** [comment]
Ok!

**Pull request merged**
