### PR TITLE
preparation for tagging v1.1

### PR DESCRIPTION
**Pull request by paskino**
release checklist https://github.com/CCPPETMR/SIRF/issues/178

### CODE REVIEW

**Comment by KrisThielemans** [comment]
I believe it falls back to master. CMake bug/feature. check the log I guess

**Comment by paskino** [comment]
I [find](https://api.travis-ci.org/v3/job/379706646/log.txt) 
```
Cloning into 'SIRF'...
error: pathspec 'v1.1.0' did not match any file(s) known to git.
CMake Error at /home/travis/build/CCPPETMR/SIRF-SuperBuild/builds/SIRF/tmp/SIRF-gitclone.cmake:65 (message):
  Failed to checkout tag: 'v1.1.0'


make[2]: *** [builds/SIRF/stamp/SIRF-download] Error 1
make[1]: *** [CMakeFiles/SIRF.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

later
```
[ 93%] Completed 'Gadgetron'
[ 93%] Built target Gadgetron
make: *** [all] Error 2
[...]
Test project /home/travis/build/CCPPETMR/SIRF-SuperBuild
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: SIRF_TESTS

1: Test command: /home/travis/.local/bin/cmake-3.7.2-Linux-x86_64/bin/ctest "-C" "Release"
1: Test timeout computed to be: 9.99988e+06
1: Test project /home/travis/build/CCPPETMR/SIRF-SuperBuild/builds/SIRF/build
1: No tests were found!!!
1/1 Test #1: SIRF_TESTS .......................   Passed    0.04 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.04 sec
Start testing: May 16 13:39 UTC
----------------------------------------------------------
End testing: May 16 13:39 UTC
05-16 13:39:23.135 ERROR [main.cpp:108] Gadgetron configuration file /home/travis/build/CCPPETMR/SIRF-SuperBuild/INSTALL/bin/..//share/gadgetron/config/gadgetron.xml not found.

travis_time:end:06e1c12e:start=1526477963112289436,finish=1526477963217765844,duration=105476408

[0Ktravis_fold:end:cache.2
[0K
Done. Your build exited with 0.
```

There are a couple of problems: if the `make` fails is not detected. If the test fail is not detected.

**Comment by KrisThielemans** [comment]
possibly we should do
```
make || travis_terminate 1
```
or something. @bathomas, @casperdcl,  is that correct? If it is, please create an issue for this (don't commit anything now!)

**Comment by paskino** [comment]
Why did you close this?

**Comment by KrisThielemans** [comment]
sorry. I closed by accident, then reopened, then merged.

**Pull request merged**
