### PR TITLE
upgrade Gadgetron and ISMRMD versions

### PR DESCRIPTION
**Pull request by paskino**
Updates for new VM based on Ubuntu 18.04 LTS.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
addresses #149

**Comment by KrisThielemans** [comment]
this looks fine to me, but I see failures on Travis... @paskino, can you have a look? We probably will have to update .travis.yml to use appropriate compilers.

Can you also add a lines to the CHANGES.md?

**Comment by KrisThielemans** [comment]
will need changes to Travis, similar to #157  (but there it's currently only for DEVEL_BUILD=On)

**Comment by KrisThielemans** [comment]
Are these versions ok?

**Comment by KrisThielemans** [comment]
@casperdcl, we're getting close to finish this. Relevant changes include using at least g++-6 and add an extra blas package. I presume this would have to be done in the docker stuff as well, but 
- I wouldn't know where the compiler is set
- somehow the devel build is still compiling anyway, which is weird.
Possibly the docker build uses Ubuntu 18.04 already?

**Comment by paskino** [comment]
GCC on Ubuntu 18.04 LTS is `gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0`

**Comment by rijobro** [comment]
I think this PR can probably closed as it was superceded by #205.

**Comment by KrisThielemans** [comment]
yes. looks that way. you could try and merge master on here and see how it looks like.

**Comment by KrisThielemans** [comment]
I've checked. This PR is obsolete since merging #205. I've put in the last few things in aac6edb59863b5a6140ec33e2e1992e6c37bb218.

**Pull request closed without merging**
