### PR TITLE
Usercount

### PR DESCRIPTION
**Pull request by casperdcl**
Related to #93

- [x] host our own database of clones (https://github.com/CCPPETMR/github-stats)
- [x] get travis to automatically update this using github's API (which only has the last fortnight's worth of clones)
- [x] automatically exclude counting travis clones

Will need to add a 3 lines to SIRF/.travis.yml to do the same there.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
looks good to me, but can you clarify where would the GITHUB_API_TOKEN come from, and who would need to create it (me?)

**Comment by casperdcl** [comment]
already done, it's a secure env var in travis. The token itself belongs to @ccp-petmr-codebot and allows full access to its repos.

**Comment by KrisThielemans** [comment]
ok. interesting how it picks that up (or possibly Travis is run via that user, I cannot remember).

Looks fine to me otherwise, so feel free to merge. Thanks!

**Comment by casperdcl** [comment]
No, I set this all up manually, but it should be future-proof and fully controlled by @ccp-petmr-codebot rather than my account.

**Pull request closed without merging**
