### PR TITLE
change FFTW_URL to ftp source

### LINKED ISSUE #320: FFTW has removed version 3.3.5 from http site
Can't download and find version 3.3.5 now and build will fail.

Should increase the version in `version_config.cmake`

### PR DESCRIPTION
**Pull request by paskino**
closes #320

### CODE REVIEW

**Comment by paskino** [comment]
I tested locally and it works, however travis fails to get the fftw file from ftp. Any ideas?

**Comment by KrisThielemans** [comment]
very long time ago we had the same problems I belief. Their `ftp` server is probably not very stable. Or Travis blocks it. Or whatever... stick to `http` I guess

**Comment by paskino** [comment]
Ok, then I Will need to change fftw version as they removed 3.3.5 from http.

**Comment by KrisThielemans** [comment]
Can put it elsewhere, e.g. or website. You've done that before

**Comment by paskino** [comment]
it seems the file is back on [http://www.fftw.org/fftw-3.3.5.tar.gz](http://www.fftw.org/fftw-3.3.5.tar.gz) so I will close the PR.

**Pull request closed without merging**
